.TH unixODBC 7 "Tue 22. Oct 2013" "version 2.3.6" "unixODBC manual pages"

.SH NAME
unixODBC \- An ODBC implementation for Unix

.SH DESCRIPTION
ODBC is an open specification for providing application developers with a
predictable API with which to access Data Sources. Data Sources include SQL
Servers and any Data Source with an ODBC Driver.

The unixODBC Project goals are to develop and promote unixODBC to be the
definitive standard for ODBC on non MS Windows platforms.

The HTML-format "Administrator Manual" shipped with \fIunixODBC\fR provides
additional details on configuration and usage to supplement these man pages.

.SH ENVIRONMENT VARIABLES

.IP \fBODBCSYSINI
Overloads path to unixODBC configuration files. By default equals to '/etc'.

.IP \fBODBCINSTINI
Overloads the name of the drivers configuration file. It is relative to
\fBODBCSYSINI\fR and by default set to 'odbcinst.ini'.

.IP \fBODBCINSTUI
Overloads the library name for UI. The final name that is searched for is
evaluated as "lib$ODBCINSTUI". By default it is set to 'odbcinstQ4', so 
the resulting library name is 'libodbcinstQ4'.

.IP \fBODBCSEARCH
Overloads the configuration mode and determines where to look for configuration
files. Must be set to one of ODBC_SYSTEM_DSN, ODBC_USER_DSN or ODBC_BOTH_DSN 
(the last one is the default value).

.IP \fBODBCINI
Overloads the path to user configuration file. By default it is set 
to "~/.odbc.ini".

.SH SEE ALSO
.BR unixODBC (7),
.BR isql (1),
.BR odbcinst (1),
.BR odbc.ini (5),
.BR odbcinst.ini (5)

.R "The \fIunixODBC\fB Administrator Manual (HTML)"

.SH AUTHORS

The authors of unixODBC are Peter Harvey <\fIpharvey@codebydesign.com\fR> and
Nick Gorham <\fInick@unixodbc.org\fR>. For the full list of contributors see the
AUTHORS file.

.SH COPYRIGHT

unixODBC is licensed under the GNU Lesser General Public License. For details
about the license, see the COPYING file.
