
cc_library(
    name = 'libodbcpsqlS',
    visibility = ['//visibility:public'],
    srcs = [
        'odbcpsqlS.c',
    ],
    copts = [
        '-DHAVE_CONFIG_H',
    ],
    deps = [
        '//:headers',
    ],
)
