
def gen_autotools_subs():
    return {
        # TODO(bd) handle the search path better
        '#undef LT_DLSEARCH_PATH\n': '#define LT_DLSEARCH_PATH "/lib:/usr/lib:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib32:/usr/lib32"\n',

        # TODO(bd) probably not the right thing to do, should
        # INSTALL_PREFIX be required as an argument to the build?
        # install prefix
        '#undef BIN_PREFIX\n': '#define BIN_PREFIX "bin"\n',
        '#undef DEFLIB_PATH\n': '#define DEFLIB_PATH "lib"\n',
        '#undef EXEC_PREFIX\n': '#define EXEC_PREFIX ""\n',
        '#undef INCLUDE_PREFIX\n': '#define INCLUDE_PREFIX "include"\n',
        '#undef LIB_PREFIX\n': '#define LIB_PREFIX "lib"\n',
        '#undef PREFIX\n': '#define PREFIX ""\n',
        '#undef SYSTEM_FILE_PATH\n': '#define SYSTEM_FILE_PATH "etc"\n',
        '#undef SYSTEM_LIB_PATH\n': '#define SYSTEM_LIB_PATH "lib"\n',

        # defines
        '#undef ASCII_ENCODING\n': '#define ASCII_ENCODING "auto-search"\n',
        '#undef ENABLE_INI_CACHING\n': '#define ENABLE_INI_CACHING /**/\n',
        '#undef HAVE_ALLOCA\n': '#define HAVE_ALLOCA 1\n',
        '#undef HAVE_ALLOCA_H\n': '#define HAVE_ALLOCA_H 1\n',
        '#undef HAVE_ARGZ_ADD\n': '#define HAVE_ARGZ_ADD 1\n',
        '#undef HAVE_ARGZ_APPEND\n': '#define HAVE_ARGZ_APPEND 1\n',
        '#undef HAVE_ARGZ_COUNT\n': '#define HAVE_ARGZ_COUNT 1\n',
        '#undef HAVE_ARGZ_CREATE_SEP\n': '#define HAVE_ARGZ_CREATE_SEP 1\n',
        '#undef HAVE_ARGZ_H\n': '#define HAVE_ARGZ_H 1\n',
        '#undef HAVE_ARGZ_INSERT\n': '#define HAVE_ARGZ_INSERT 1\n',
        '#undef HAVE_ARGZ_NEXT\n': '#define HAVE_ARGZ_NEXT 1\n',
        '#undef HAVE_ARGZ_STRINGIFY\n': '#define HAVE_ARGZ_STRINGIFY 1\n',
        '#undef HAVE_ATOLL\n': '#define HAVE_ATOLL 1\n',
        '#undef HAVE_CLOCK_GETTIME\n': '#define HAVE_CLOCK_GETTIME 1\n',
        '#undef HAVE_CLOSEDIR\n': '#define HAVE_CLOSEDIR 1\n',
        '#undef HAVE_CRYPT_H\n': '#define HAVE_CRYPT_H 1\n',
        '#undef HAVE_DIRENT_H\n': '#define HAVE_DIRENT_H 1\n',
        '#undef HAVE_DLERROR\n': '#define HAVE_DLERROR 1\n',
        '#undef HAVE_DLFCN_H\n': '#define HAVE_DLFCN_H 1\n',
        '#undef HAVE_ENDPWENT\n': '#define HAVE_ENDPWENT 1\n',
        '#undef HAVE_ERROR_T\n': '#define HAVE_ERROR_T 1\n',
        '#undef HAVE_FSEEKO\n': '#define HAVE_FSEEKO 1\n',
        '#undef HAVE_FTIME\n': '#define HAVE_FTIME 1\n',
        '#undef HAVE_FUNC_GETPWUID_R_5\n': '#define HAVE_FUNC_GETPWUID_R_5 1\n',
        '#undef HAVE_GETPID\n': '#define HAVE_GETPID 1\n',
        '#undef HAVE_GETPWUID\n': '#define HAVE_GETPWUID 1\n',
        '#undef HAVE_GETPWUID_R\n': '#define HAVE_GETPWUID_R 1\n',
        '#undef HAVE_GETTIMEOFDAY\n': '#define HAVE_GETTIMEOFDAY 1\n',
        '#undef HAVE_GETUID\n': '#define HAVE_GETUID 1\n',
        '#undef HAVE_ICONV\n': '#define HAVE_ICONV 1\n',
        '#undef HAVE_INTPTR_T\n': '#define HAVE_INTPTR_T 1\n',
        '#undef HAVE_INTTYPES_H\n': '#define HAVE_INTTYPES_H 1\n',
        '#undef HAVE_LANGINFO_CODESET\n': '#define HAVE_LANGINFO_CODESET 1\n',
        '#undef HAVE_LANGINFO_H\n': '#define HAVE_LANGINFO_H 1\n',
        '#undef HAVE_LIBCRYPT\n': '#define HAVE_LIBCRYPT /**/\n',
        '#undef HAVE_LIBDL\n': '#define HAVE_LIBDL 1\n',
        '#undef HAVE_LIBDLLOADER\n': '#define HAVE_LIBDLLOADER 1\n',
        '#undef HAVE_LIBPTHREAD\n': '#define HAVE_LIBPTHREAD 1\n',
        '#undef HAVE_LIMITS_H\n': '#define HAVE_LIMITS_H 1\n',
        '#undef HAVE_LOCALE_H\n': '#define HAVE_LOCALE_H 1\n',
        '#undef HAVE_LOCALTIME_R\n': '#define HAVE_LOCALTIME_R 1\n',
        '#undef HAVE_LONG_LONG\n': '#define HAVE_LONG_LONG 1\n',
        '#undef HAVE_LTDL\n': '#define HAVE_LTDL 1\n',
        '#undef HAVE_MALLOC_H\n': '#define HAVE_MALLOC_H 1\n',
        '#undef HAVE_NL_LANGINFO\n': '#define HAVE_NL_LANGINFO 1\n',
        '#undef HAVE_OPENDIR\n': '#define HAVE_OPENDIR 1\n',
        '#undef HAVE_PRELOADED_SYMBOLS\n': '#define HAVE_PRELOADED_SYMBOLS 1\n',
        '#undef HAVE_PTRDIFF_T\n': '#define HAVE_PTRDIFF_T 1\n',
        '#undef HAVE_PUTENV\n': '#define HAVE_PUTENV 1\n',
        '#undef HAVE_PWD_H\n': '#define HAVE_PWD_H 1\n',
        '#undef HAVE_READDIR\n': '#define HAVE_READDIR 1\n',
        '#undef HAVE_SETENV\n': '#define HAVE_SETENV 1\n',
        '#undef HAVE_SETLOCALE\n': '#define HAVE_SETLOCALE 1\n',
        '#undef HAVE_SETVBUF\n': '#define HAVE_SETVBUF 1\n',
        '#undef HAVE_SNPRINTF\n': '#define HAVE_SNPRINTF 1\n',
        '#undef HAVE_SOCKET\n': '#define HAVE_SOCKET 1\n',
        '#undef HAVE_STDARG_H\n': '#define HAVE_STDARG_H 1\n',
        '#undef HAVE_STDDEF_H\n': '#define HAVE_STDDEF_H 1\n',
        '#undef HAVE_STDINT_H\n': '#define HAVE_STDINT_H 1\n',
        '#undef HAVE_STDIO_H\n': '#define HAVE_STDIO_H 1\n',
        '#undef HAVE_STDLIB_H\n': '#define HAVE_STDLIB_H 1\n',
        '#undef HAVE_STRCASECMP\n': '#define HAVE_STRCASECMP 1\n',
        '#undef HAVE_STRCHR\n': '#define HAVE_STRCHR 1\n',
        '#undef HAVE_STRDUP\n': '#define HAVE_STRDUP 1\n',
        '#undef HAVE_STRING_H\n': '#define HAVE_STRING_H 1\n',
        '#undef HAVE_STRINGS_H\n': '#define HAVE_STRINGS_H 1\n',
        '#undef HAVE_STRLCAT\n': '#define HAVE_STRLCAT 1\n',
        '#undef HAVE_STRLCPY\n': '#define HAVE_STRLCPY 1\n',
        '#undef HAVE_STRNCASECMP\n': '#define HAVE_STRNCASECMP 1\n',
        '#undef HAVE_STRSTR\n': '#define HAVE_STRSTR 1\n',
        '#undef HAVE_STRTOL\n': '#define HAVE_STRTOL 1\n',
        '#undef HAVE_STRTOLL\n': '#define HAVE_STRTOLL 1\n',
        '#undef HAVE_SYS_SEM_H\n': '#define HAVE_SYS_SEM_H 1\n',
        '#undef HAVE_SYS_STAT_H\n': '#define HAVE_SYS_STAT_H 1\n',
        '#undef HAVE_SYS_TIMEB_H\n': '#define HAVE_SYS_TIMEB_H 1\n',
        '#undef HAVE_SYS_TIME_H\n': '#define HAVE_SYS_TIME_H 1\n',
        '#undef HAVE_SYS_TYPES_H\n': '#define HAVE_SYS_TYPES_H 1\n',
        '#undef HAVE_TIME\n': '#define HAVE_TIME 1\n',
        '#undef HAVE_TIME_H\n': '#define HAVE_TIME_H 1\n',
        '#undef HAVE_UNISTD_H\n': '#define HAVE_UNISTD_H 1\n',
        '#undef HAVE_VPRINTF\n': '#define HAVE_VPRINTF 1\n',
        '#undef HAVE_VSNPRINTF\n': '#define HAVE_VSNPRINTF 1\n',
        '#undef HAVE_WORKING_ARGZ\n': '#define HAVE_WORKING_ARGZ 1\n',
        '#undef ICONV_CONST\n': '#define ICONV_CONST\n',
        '#undef LT_LIBEXT\n': '#define LT_LIBEXT "a"\n',
        '#undef LT_LIBPREFIX\n': '#define LT_LIBPREFIX "lib"\n',
        '#undef LT_MODULE_EXT\n': '#define LT_MODULE_EXT ".so"\n',
        '#undef LT_MODULE_PATH_VAR\n': '#define LT_MODULE_PATH_VAR "LD_LIBRARY_PATH"\n',
        '#undef LT_OBJDIR\n': '#define LT_OBJDIR ".libs/"\n',
        '#undef PACKAGE_BUGREPORT\n': '#define PACKAGE_BUGREPORT "nick@unixodbc.org"\n',
        '#undef PACKAGE_NAME\n': '#define PACKAGE_NAME "unixODBC"\n',
        '#undef PACKAGE_TARNAME\n': '#define PACKAGE_TARNAME "unixODBC"\n',
        '#undef PACKAGE\n': '#define PACKAGE "unixODBC"\n',
        '#undef PACKAGE_URL\n': '#define PACKAGE_URL ""\n',
        '#undef PLATFORM64\n': '#define PLATFORM64 /**/\n',
        '#undef SHLIBEXT\n': '#define SHLIBEXT ".so"\n',
        '#undef SIZEOF_LONG\n': '#define SIZEOF_LONG 8\n',
        '#undef SIZEOF_LONG_INT\n': '#define SIZEOF_LONG_INT 8\n',
        '#undef STATS_FTOK_NAME\n': '#define STATS_FTOK_NAME "odbc.ini"\n',
        '#undef STDC_HEADERS\n': '#define STDC_HEADERS 1\n',
        '#undef STRICT_ODBC_ERROR\n': '#define STRICT_ODBC_ERROR /**/\n',
        '#undef TIME_WITH_SYS_TIME\n': '#define TIME_WITH_SYS_TIME 1\n',
        '#undef UNICODE_ENCODING\n': '#define UNICODE_ENCODING "auto-search"\n',
        '#undef UNIXODBC\n': '#define UNIXODBC /**/\n',
        '#undef UNIXODBC_SOURCE\n': '#define UNIXODBC_SOURCE /**/\n',
        # undef removals
        '#undef _ALL_SOURCE\n': '/* #undef _ALL_SOURCE */\n',
        '#undef C_ALLOCA\n': '/* #undef C_ALLOCA */\n',
        '#undef COLLECT_STATS\n': '/* #undef COLLECT_STATS */\n',
        '#undef const\n': '/* #undef const */\n',
        '#undef CRAY_STACKSEG_END\n': '/* #undef CRAY_STACKSEG_END */\n',
        '#undef ENABLE_DRIVER_ICONV\n': '/* #undef ENABLE_DRIVER_ICONV */\n',
        '#undef error_t\n': '/* #undef error_t */\n',
        '#undef __error_t_defined\n': '/* #undef __error_t_defined */\n',
        '#undef FAST_HANDLE_VALIDATE\n': '/* #undef FAST_HANDLE_VALIDATE */\n',
        '#undef _FILE_OFFSET_BITS\n': '/* #undef _FILE_OFFSET_BITS */\n',
        '#undef gid_t\n': '/* #undef gid_t */\n',
        '#undef HAVE_DECL_CYGWIN_CONV_PATH\n': '/* #undef HAVE_DECL_CYGWIN_CONV_PATH */\n',
        '#undef HAVE_DLD\n': '/* #undef HAVE_DLD */\n',
        '#undef HAVE_DLD_H\n': '/* #undef HAVE_DLD_H */\n',
        '#undef HAVE_DL_H\n': '/* #undef HAVE_DL_H */\n',
        '#undef HAVE_DOPRNT\n': '/* #undef HAVE_DOPRNT */\n',
        '#undef HAVE_DYLD\n': '/* #undef HAVE_DYLD */\n',
        '#undef HAVE_EDITLINE\n': '/* #undef HAVE_EDITLINE */\n',
        '#undef HAVE_EDITLINE_READLINE_H\n': '/* #undef HAVE_EDITLINE_READLINE_H */\n',
        '#undef HAVE_FTOK\n': '/* #undef HAVE_FTOK */\n',
        '#undef HAVE_FUNC_GETPWUID_R_4\n': '/* #undef HAVE_FUNC_GETPWUID_R_4 */\n',
        '#undef HAVE_LIBPTH\n': '/* #undef HAVE_LIBPTH */\n',
        '#undef HAVE_LIBTHREAD\n': '/* #undef HAVE_LIBTHREAD */\n',
        '#undef HAVE_MACH_O_DYLD_H\n': '/* #undef HAVE_MACH_O_DYLD_H */\n',
        '#undef HAVE_MEMORY_H\n': '/* #undef HAVE_MEMORY_H */\n',
        '#undef HAVE_MSQL_H\n': '/* #undef HAVE_MSQL_H */\n',
        '#undef HAVE_NDIR_H\n': '/* #undef HAVE_NDIR_H */\n',
        '#undef HAVE_READLINE\n': '/* #undef HAVE_READLINE */\n',
        '#undef HAVE_READLINE_HISTORY_H\n': '/* #undef HAVE_READLINE_HISTORY_H */\n',
        '#undef HAVE_SCANDIR\n': '/* #undef HAVE_SCANDIR */\n',
        '#undef HAVE_SEMGET\n': '/* #undef HAVE_SEMGET */\n',
        '#undef HAVE_SEMOP\n': '/* #undef HAVE_SEMOP */\n',
        '#undef HAVE_SHL_LOAD\n': '/* #undef HAVE_SHL_LOAD */\n',
        '#undef HAVE_SHMGET\n': '/* #undef HAVE_SHMGET */\n',
        '#undef HAVE_STRICMP\n': '/* #undef HAVE_STRICMP */\n',
        '#undef HAVE_STRNICMP\n': '/* #undef HAVE_STRNICMP */\n',
        '#undef HAVE_SYNCH_H\n': '/* #undef HAVE_SYNCH_H */\n',
        '#undef HAVE_SYS_DIR_H\n': '/* #undef HAVE_SYS_DIR_H */\n',
        '#undef HAVE_SYS_DL_H\n': '/* #undef HAVE_SYS_DL_H */\n',
        '#undef HAVE_SYS_MALLOC_H\n': '/* #undef HAVE_SYS_MALLOC_H */\n',
        '#undef HAVE_SYS_NDIR_H\n': '/* #undef HAVE_SYS_NDIR_H */\n',
        '#undef HAVE_VARARGS_H\n': '/* #undef HAVE_VARARGS_H */\n',
        '#undef intptr_t\n': '/* #undef intptr_t */\n',
        '#undef _LARGE_FILES\n': '/* #undef _LARGE_FILES */\n',
        '#undef _LARGEFILE_SOURCE\n': '/* #undef _LARGEFILE_SOURCE */\n',
        '#undef _LONG_LONG\n': '/* #undef _LONG_LONG */\n',
        '#undef LTDL_DLOPEN_DEPLIBS\n': '/* #undef LTDL_DLOPEN_DEPLIBS */\n',
        '#undef LT_SHARED_EXT\n': '/* #undef LT_SHARED_EXT */\n',
        '#undef LT_SHARED_LIB_MEMBER\n': '/* #undef LT_SHARED_LIB_MEMBER */\n',
        '#undef MODULEDIR\n': '/* #undef MODULEDIR */\n',
        '#undef NEED_SEMUNDO_UNION\n': '/* #undef NEED_SEMUNDO_UNION */\n',
        '#undef NEED_USCORE\n': '/* #undef NEED_USCORE */\n',
        '#undef OSXHEADER\n': '/* #undef OSXHEADER */\n',
        '#undef QNX_LIBLTDL\n': '/* #undef QNX_LIBLTDL */\n',
        '#undef size_t\n': '/* #undef size_t */\n',
        '#undef STACK_DIRECTION\n': '/* #undef STACK_DIRECTION */\n',
        '#undef _THREAD_SAFE\n': '/* #undef _THREAD_SAFE */\n',
        '#undef TM_IN_SYS_TIME\n': '/* #undef TM_IN_SYS_TIME */\n',
        '#undef uid_t\n': '/* #undef uid_t */\n',
        '#undef WITH_HANDLE_REDIRECT\n': '/* #undef WITH_HANDLE_REDIRECT */\n',
        '#undef WITH_SHARDENV\n': '/* #undef WITH_SHARDENV */\n',
        '#undef WITH_UTF8_INI\n': '/* #undef WITH_UTF8_INI */\n',
        '#undef YYTEXT_POINTER\n': '/* #undef YYTEXT_POINTER */\n',
    }

AUTOTOOLS_SUBS = gen_autotools_subs()
