
load('@bazel_skylib//rules:expand_template.bzl', 'expand_template')
load('@module_versions//:versions.bzl', 'UNIXODBC_VERSION')

expand_template(
    name = 'config_header',
    out = 'include/config.h',
    substitutions = {
        '@INSTALL_PREFIX@': '/usr/local',
        '@MODULE_VERSION@': UNIXODBC_VERSION
    },
    template = 'bazel/config.h.linux',
)

expand_template(
    name = 'unixodbc_conf_header',
    out = 'include/unixODBC/unixodbc_conf.h',
    substitutions = {
        '@INSTALL_PREFIX@': '/usr/local',
    },
    template = 'bazel/unixodbc_conf.h.linux',
)

filegroup(
    name = 'unixodbc_header_in',
    srcs = ['bazel/unixodbc.h.linux'],
)

genrule(
    name = 'unixodbc_header',
    srcs = ['unixodbc_header_in'],
    outs = ['include/unixodbc.h'],
    cmd = 'cp $(SRCS) $(OUTS)'
)

cc_library(
    name = 'headers',
    visibility = ['//visibility:public'],
    hdrs = [
        'include/sqlspi.h',
        'include/sqlucode.h',
        'include/sqp.h',
        'include/lst.h',
        'include/odbcinst.h',
        'include/sql.h',
        'include/sqltypes.h',
        'include/sqlext.h',
        'include/odbctrace.h',
        'include/odbcinstext.h',
        'include/uodbc_stats.h',
        'include/ini.h',
        'include/uodbc_extras.h',
        'include/log.h',
        'include/odbctrac.h',
        'include/autotest.h',
        ':config_header',
        ':unixodbc_header',
    ],
    strip_include_prefix = 'include',
)

cc_library(
    name = 'libodbc',
    visibility = ['//visibility:public'],
    srcs = [
        'DriverManager/SQLAllocConnect.c',
        'DriverManager/SQLAllocEnv.c',
        'DriverManager/SQLAllocHandle.c',
        'DriverManager/SQLAllocHandleStd.c',
        'DriverManager/SQLAllocStmt.c',
        'DriverManager/SQLBindCol.c',
        'DriverManager/SQLBindParam.c',
        'DriverManager/SQLBindParameter.c',
        'DriverManager/SQLBrowseConnect.c',
        'DriverManager/SQLBulkOperations.c',
        'DriverManager/SQLCancel.c',
        'DriverManager/SQLCancelHandle.c',
        'DriverManager/SQLCloseCursor.c',
        'DriverManager/SQLColAttribute.c',
        'DriverManager/SQLColAttributes.c',
        'DriverManager/SQLColumnPrivileges.c',
        'DriverManager/SQLColumns.c',
        'DriverManager/SQLConnect.c',
        'DriverManager/SQLCopyDesc.c',
        'DriverManager/SQLDataSources.c',
        'DriverManager/SQLDescribeCol.c',
        'DriverManager/SQLDescribeParam.c',
        'DriverManager/SQLDisconnect.c',
        'DriverManager/SQLDriverConnect.c',
        'DriverManager/SQLDrivers.c',
        'DriverManager/SQLEndTran.c',
        'DriverManager/SQLError.c',
        'DriverManager/SQLExecDirect.c',
        'DriverManager/SQLExecute.c',
        'DriverManager/SQLExtendedFetch.c',
        'DriverManager/SQLFetch.c',
        'DriverManager/SQLFetchScroll.c',
        'DriverManager/SQLForeignKeys.c',
        'DriverManager/SQLFreeConnect.c',
        'DriverManager/SQLFreeEnv.c',
        'DriverManager/SQLFreeHandle.c',
        'DriverManager/SQLFreeStmt.c',
        'DriverManager/SQLGetConnectAttr.c',
        'DriverManager/SQLGetConnectOption.c',
        'DriverManager/SQLGetCursorName.c',
        'DriverManager/SQLGetData.c',
        'DriverManager/SQLGetDescField.c',
        'DriverManager/SQLGetDescRec.c',
        'DriverManager/SQLGetDiagField.c',
        'DriverManager/SQLGetDiagRec.c',
        'DriverManager/SQLGetEnvAttr.c',
        'DriverManager/SQLGetFunctions.c',
        'DriverManager/SQLGetInfo.c',
        'DriverManager/SQLGetStmtAttr.c',
        'DriverManager/SQLGetStmtOption.c',
        'DriverManager/SQLGetTypeInfo.c',
        'DriverManager/SQLMoreResults.c',
        'DriverManager/SQLNativeSql.c',
        'DriverManager/SQLNumParams.c',
        'DriverManager/SQLNumResultCols.c',
        'DriverManager/SQLParamData.c',
        'DriverManager/SQLParamOptions.c',
        'DriverManager/SQLPrepare.c',
        'DriverManager/SQLPrimaryKeys.c',
        'DriverManager/SQLProcedureColumns.c',
        'DriverManager/SQLProcedures.c',
        'DriverManager/SQLPutData.c',
        'DriverManager/SQLRowCount.c',
        'DriverManager/SQLSetConnectAttr.c',
        'DriverManager/SQLSetConnectOption.c',
        'DriverManager/SQLSetCursorName.c',
        'DriverManager/SQLSetDescField.c',
        'DriverManager/SQLSetDescRec.c',
        'DriverManager/SQLSetEnvAttr.c',
        'DriverManager/SQLSetParam.c',
        'DriverManager/SQLSetPos.c',
        'DriverManager/SQLSetScrollOptions.c',
        'DriverManager/SQLSetStmtAttr.c',
        'DriverManager/SQLSetStmtOption.c',
        'DriverManager/SQLSpecialColumns.c',
        'DriverManager/SQLStatistics.c',
        'DriverManager/SQLTablePrivileges.c',
        'DriverManager/SQLTables.c',
        'DriverManager/SQLTransact.c',
        'DriverManager/SQLBrowseConnectW.c',
        'DriverManager/SQLColAttributeW.c',
        'DriverManager/SQLColAttributesW.c',
        'DriverManager/SQLColumnPrivilegesW.c',
        'DriverManager/SQLColumnsW.c',
        'DriverManager/SQLConnectW.c',
        'DriverManager/SQLDataSourcesW.c',
        'DriverManager/SQLDescribeColW.c',
        'DriverManager/SQLDriverConnectW.c',
        'DriverManager/SQLDriversW.c',
        'DriverManager/SQLErrorW.c',
        'DriverManager/SQLExecDirectW.c',
        'DriverManager/SQLForeignKeysW.c',
        'DriverManager/SQLGetConnectAttrW.c',
        'DriverManager/SQLGetConnectOptionW.c',
        'DriverManager/SQLGetCursorNameW.c',
        'DriverManager/SQLGetDescFieldW.c',
        'DriverManager/SQLGetDescRecW.c',
        'DriverManager/SQLGetDiagFieldW.c',
        'DriverManager/SQLGetDiagRecW.c',
        'DriverManager/SQLGetInfoW.c',
        'DriverManager/SQLGetStmtAttrW.c',
        'DriverManager/SQLGetTypeInfoW.c',
        'DriverManager/SQLNativeSqlW.c',
        'DriverManager/SQLPrepareW.c',
        'DriverManager/SQLPrimaryKeysW.c',
        'DriverManager/SQLProcedureColumnsW.c',
        'DriverManager/SQLProceduresW.c',
        'DriverManager/SQLSetConnectAttrW.c',
        'DriverManager/SQLSetConnectOptionW.c',
        'DriverManager/SQLSetCursorNameW.c',
        'DriverManager/SQLSetDescFieldW.c',
        'DriverManager/SQLSetStmtAttrW.c',
        'DriverManager/SQLSetStmtOptionW.c',
        'DriverManager/SQLSpecialColumnsW.c',
        'DriverManager/SQLStatisticsW.c',
        'DriverManager/SQLTablePrivilegesW.c',
        'DriverManager/SQLTablesW.c',
        'DriverManager/__connection.c',
        'DriverManager/__handles.c',
        'DriverManager/__info.c',
        'DriverManager/__stats.h',
        'DriverManager/__stats.c',
        'DriverManager/__attribute.c',
    ],
    hdrs = [
        'DriverManager/drivermanager.h',
    ],
    copts = ['-DHAVE_TIME_H'],
    linkopts = [
        '-lltdl',
        '-ldl',
    ],
    deps = [
        '//lst:liblstlc',
        '//log:libloglc',
        '//ini:libinilc',
        '//odbcinst:libodbcinstlc',
        '//:headers',
    ],
    includes = ['DriverManager'],
    strip_include_prefix = 'DriverManager',
)
