
cc_library(
    name = 'libodbcextraslc',
    visibility = ['//visibility:public'],
    srcs = [
        'strcasecmp.c',
        'snprintf.c',
    ],
    copts = [
        '-DHAVE_CONFIG_H',
    ],
    deps = [
        '//:headers',
    ],
)
