
cc_library(
    name = 'libodbcextraslc',
    visibility = ['//visibility:public'],
    srcs = [
        'strcasecmp.c',
        'snprintf.c',
    ],
    linkstatic = True,
    deps = [
        '//:headers',
    ],
)
